import * as THREE from "three";
import { CONFIG, ASSETS, ANIMATIONS } from "./config.js";
import { createInput } from "./systems/input.js";
import { createCameraController } from "./systems/camera.js";
import { createPlayer } from "./entities/player.js";

const scene=new THREE.Scene(); scene.background=new THREE.Color(0xa8d8ec); scene.fog=new THREE.Fog(0xa8d8ec,24,54);
const camera=new THREE.PerspectiveCamera(CONFIG.camera.fov,innerWidth/innerHeight,CONFIG.camera.near,CONFIG.camera.far);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xfff5dd,0x496448,2.2)); const sun=new THREE.DirectionalLight(0xffedc4,2.5); sun.position.set(-7,12,7); sun.castShadow=true; scene.add(sun);
const tl=new THREE.TextureLoader(); const grass=await tl.loadAsync(ASSETS.grass); grass.wrapS=grass.wrapT=THREE.RepeatWrapping; grass.repeat.set(CONFIG.grassRepeat,CONFIG.grassRepeat); grass.colorSpace=THREE.SRGBColorSpace;
const ground=new THREE.Mesh(new THREE.PlaneGeometry(CONFIG.worldSize,CONFIG.worldSize),new THREE.MeshStandardMaterial({map:grass,roughness:1})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; ground.renderOrder=CONFIG.depth.groundOrder; scene.add(ground);
const pathTex=await tl.loadAsync(ASSETS.dirtPath); pathTex.colorSpace=THREE.SRGBColorSpace; const pathMat=new THREE.MeshBasicMaterial({map:pathTex,transparent:false,alphaTest:CONFIG.depth.pathAlphaTest,depthTest:true,depthWrite:true,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}); const path=new THREE.Mesh(new THREE.PlaneGeometry(CONFIG.pathSize,CONFIG.pathSize),pathMat); path.rotation.x=-Math.PI/2; path.position.y=CONFIG.depth.pathY; path.renderOrder=CONFIG.depth.pathOrder; scene.add(path);
const status=document.querySelector("#status"); let player; try{player=await createPlayer({url:ASSETS.player,height:CONFIG.playerHeight,renderOrder:CONFIG.depth.playerOrder,animations:ANIMATIONS}); scene.add(player.root); status.textContent="Liora ready • 7 animations ✓";}catch(err){console.error(err);status.textContent="Player load failed";}
const input=createInput(), cam=createCameraController(camera,CONFIG.camera), clock=new THREE.Clock(), target=new THREE.Vector3();
document.querySelectorAll("[data-action]").forEach(btn=>btn.onclick=()=>{if(!player)return; const key=btn.dataset.action; if(player.playSpecial(ANIMATIONS[key],()=>btn.classList.remove("active")))btn.classList.add("active");});
function animate(){requestAnimationFrame(animate); const dt=Math.min(clock.getDelta(),.04); if(player){const d=input.get(); if(!player.isSpecial()&&d.m>.05){const run=d.m>CONFIG.runThreshold,speed=run?CONFIG.runSpeed:CONFIG.walkSpeed; player.root.position.x+=d.x*speed*dt; player.root.position.z+=d.z*speed*dt; const a=Math.atan2(d.x,d.z); let diff=Math.atan2(Math.sin(a-player.root.rotation.y),Math.cos(a-player.root.rotation.y)); player.root.rotation.y+=diff*Math.min(1,10*dt); player.fadeTo(run?ANIMATIONS.run:ANIMATIONS.walk,.15,true);} else if(!player.isSpecial()) player.fadeTo(ANIMATIONS.idle,.18,true); player.mixer.update(dt); player.root.position.x=THREE.MathUtils.clamp(player.root.position.x,-CONFIG.worldLimit,CONFIG.worldLimit); player.root.position.z=THREE.MathUtils.clamp(player.root.position.z,-CONFIG.worldLimit,CONFIG.worldLimit); target.set(player.root.position.x,.7,player.root.position.z);} cam.update(target,dt); renderer.render(scene,camera);} animate();
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
